travis:
  secure:
    BINSTAR_TOKEN: oP2Ucx6AUmpDUdhNJOk7e5DZV0flGt6V3WBpyMk4TyNHAQnY/PxDieGYUor6yfo/rluu2TwH/OvogX8CJmYEDynhkarnjpHHVHcVDbmxhMrTBDmMbu1i3TjjP4roqk0nhdTeiA81EAzcqE7Bc8PBidk40ZjtMBj9HVBFOCjyXwvYI4u8PAiRrESijtGp9cmbJUUi1dTF1BeIgtfWZzWdQq4jYI8ifWfszx+YtW+mgq1jGp6g1cLAzivCBKW9MnUsOjFgCZ16Oz8pC6ycQqnPZh54N2Yxo5hIZq94dCfoNiu9Qe3r5Hzf+qav5SV8i8Dspt7imFY1hMSToXYk1l7KQHMBnPbx60pvaCq/WygF5Uoze1RhpyDriQkV3zbS31F434zBibkZK0r2hBAw7xSNBOQJlhnpOgjcmNweCswmOk7YXX6SQEyPTV7fan/F0t5SbKRrv3fRWpeQu30cCMfcj5OPE0XZHQ25jqjuHqEyZJyktkGozjjKxFI+0vhnwR57irDjXv4bTrRku6t1ahuzuz91xJ8pk+i2pLOzOJ8g23P62B+YOm2PMDhil3s8PwDrHMTy6XsK7Inkbz7fbovHG6Oys+ye2SkcKekWGnrJGZ2bStYVoT0GAEv4GfQsy/H/VfrW8C/hb4be/96JwABGwZ69I14UQdIVI8JkTrMuRFg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
