travis:
  secure:
    BINSTAR_TOKEN: K2QLoM03xkM7/fb8jUvubV+NhfLxg0Dghxev/UyAiw1fvOIj2EVQN+oVdNl7xVGFTP0L9vNhI+8SI8Zh7ixuHEYZSikdjPhA6j/O26XF2sagneT3HPi1DsUwKujDClucbLcpUhmcrppJIsDbRiQZYZh6XMBhQ1fSZwaZCpZSyEzN7AwX1NlJT6OGJOZrAnuVosb1T4prfTUbxInsbttEZUn/idZUh+mvMhzPBwhhe/ctenvTSHz7HFwmCOwgK02p0uw3oxiFx07TKX1n14B9nXDAPH90/4EPhCOtZ8rNOSVbCQMtPUJOCKqPeZhIN5oAe1B+r7UIPZCHC4+5l6/cGXv2rxspMNxPQSQUM8Djpi8mSBjahUWRLIoBlPmYw5sqdDRC223uZ68ESwi9+rI373LFmP6xmbc5RhnB7YX19wHdM2fT19TPz6OA7P1FHbsm6/fGTmrSNRvi4HMTP8Won/6nEOGVOZ1hO6XrZSz1+noYsDUJxVY+1At0mISMf6L6a4t9oSIv4qk23nUobRuHvSfqj7zKUHAF/Kq6ng3p0SiAqOKcqsdbq9gbYd7RIFGKBH4TEx1IZGxUr/WFdkU3e40DYsBbmhKSNN5vx9xfTVAQ4XBcm3UFDCnQOrq4UouvOYJ4WQlVOi2liAU7hC8xoEBmnSSgitVap5zzkmSIDRM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
