travis:
  secure:
    BINSTAR_TOKEN: GBZsfMbpndldDX5U+TTxEk23YgxEOIuu6lRlHDXSdALULbqb2RTLEkDorrXntgeuGsF1FcuBT5U2J3Z1StvXrDyhJOQ+qg57Jxszb6Zw0pVAxIc63vcf6mI6fteuLJXnIE+pUuK1omjCqHa/XaCYRbkf/e6pv4WpkVw7zNQKCFPriyoBbow5CtHyvynWX6aIw3LP9kRJwA24m0NZ/JAr/PlmaHZusFJ/hElKNgSJJQJNVkUuMb2UNSqkKx2vFw+qDjjwEnGwMENg3Px+lExDpsumglkx7bt5wRS+viS31OwzXIebjRT1M6OaNekS1U0q/bIKPinroPxgZoOkmRMydRoGDUcHn9WfjP3/MAvenGSw8lPEjv7cPCqAdhNTbikdnv3ORjTWRGNjsiHFzIuFAKw2nH1TUyesdocj5q5f9azfSaoBuyzun52TCeQ4ewduyBZVCmQO1Sxzg9N84upYpWuPW0smAAPh+Hbp3ryOcJedAOZU5w4dI1YvrjZ+Mdj49u60QetdxiUzXWn/xBRcIFusR3BqD8qXMeZu5J43qFB1wlr51TfdD2m0GffQJG4togfZALdLAnCHuCHom50N8LnG1ION/rdpA+U5VmA5+qwXRFOTTIWrls7qRS9xHGOiL6RlYhdIVItSwgOPv0wGLWFMXovNyftaYXFIsDTBVgs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
